// Code generated by protoc-gen-go.
// source: github.com/HailoOSS/provisioning-manager-service/proto/levels.proto
// DO NOT EDIT!

/*
Package com_HailoOSS_kernel_provisioningmanager is a generated protocol buffer package.

It is generated from these files:
	github.com/HailoOSS/provisioning-manager-service/proto/levels.proto

It has these top-level messages:
*/
package com_HailoOSS_kernel_provisioningmanager

import proto "github.com/HailoOSS/protobuf/proto"
import json "encoding/json"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type Level int32

const (
	Level_HALT      Level = 0
	Level_PLATFORM  Level = 1
	Level_CRITICAL  Level = 2
	Level_ESSENTIAL Level = 3
	Level_DEGRADED  Level = 4
	Level_ALL       Level = 5
)

var Level_name = map[int32]string{
	0: "HALT",
	1: "PLATFORM",
	2: "CRITICAL",
	3: "ESSENTIAL",
	4: "DEGRADED",
	5: "ALL",
}
var Level_value = map[string]int32{
	"HALT":      0,
	"PLATFORM":  1,
	"CRITICAL":  2,
	"ESSENTIAL": 3,
	"DEGRADED":  4,
	"ALL":       5,
}

func (x Level) Enum() *Level {
	p := new(Level)
	*p = x
	return p
}
func (x Level) String() string {
	return proto.EnumName(Level_name, int32(x))
}
func (x Level) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *Level) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Level_value, data, "Level")
	if err != nil {
		return err
	}
	*x = Level(value)
	return nil
}

func init() {
	proto.RegisterEnum("com.HailoOSS.kernel.provisioningmanager.Level", Level_name, Level_value)
}
