// Code generated by protoc-gen-go.
// source: github.com/HailoOSS/provisioning-manager-service/proto/provisioner.proto
// DO NOT EDIT!

/*
Package com_HailoOSS_kernel_provisioningmanager is a generated protocol buffer package.

It is generated from these files:
	github.com/HailoOSS/provisioning-manager-service/proto/provisioner.proto

It has these top-level messages:
	Resource
	Service
	Machine
	Provisioner
*/
package com_HailoOSS_kernel_provisioningmanager

import proto "github.com/HailoOSS/protobuf/proto"
import json "encoding/json"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type Resource struct {
	Cpu              *float64 `protobuf:"fixed64,1,opt,name=cpu" json:"cpu,omitempty"`
	Memory           *uint64  `protobuf:"varint,2,opt,name=memory" json:"memory,omitempty"`
	Disk             *uint64  `protobuf:"varint,3,opt,name=disk" json:"disk,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Resource) Reset()         { *m = Resource{} }
func (m *Resource) String() string { return proto.CompactTextString(m) }
func (*Resource) ProtoMessage()    {}

func (m *Resource) GetCpu() float64 {
	if m != nil && m.Cpu != nil {
		return *m.Cpu
	}
	return 0
}

func (m *Resource) GetMemory() uint64 {
	if m != nil && m.Memory != nil {
		return *m.Memory
	}
	return 0
}

func (m *Resource) GetDisk() uint64 {
	if m != nil && m.Disk != nil {
		return *m.Disk
	}
	return 0
}

type Service struct {
	Name             *string   `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Version          *string   `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
	Usage            *Resource `protobuf:"bytes,3,opt,name=usage" json:"usage,omitempty"`
	Allocation       *Resource `protobuf:"bytes,4,opt,name=allocation" json:"allocation,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *Service) Reset()         { *m = Service{} }
func (m *Service) String() string { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()    {}

func (m *Service) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Service) GetVersion() string {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return ""
}

func (m *Service) GetUsage() *Resource {
	if m != nil {
		return m.Usage
	}
	return nil
}

func (m *Service) GetAllocation() *Resource {
	if m != nil {
		return m.Allocation
	}
	return nil
}

type Machine struct {
	Cores            *uint64   `protobuf:"varint,1,req,name=cores" json:"cores,omitempty"`
	Memory           *uint64   `protobuf:"varint,2,req,name=memory" json:"memory,omitempty"`
	Disk             *uint64   `protobuf:"varint,3,req,name=disk" json:"disk,omitempty"`
	Usage            *Resource `protobuf:"bytes,4,opt,name=usage" json:"usage,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *Machine) Reset()         { *m = Machine{} }
func (m *Machine) String() string { return proto.CompactTextString(m) }
func (*Machine) ProtoMessage()    {}

func (m *Machine) GetCores() uint64 {
	if m != nil && m.Cores != nil {
		return *m.Cores
	}
	return 0
}

func (m *Machine) GetMemory() uint64 {
	if m != nil && m.Memory != nil {
		return *m.Memory
	}
	return 0
}

func (m *Machine) GetDisk() uint64 {
	if m != nil && m.Disk != nil {
		return *m.Disk
	}
	return 0
}

func (m *Machine) GetUsage() *Resource {
	if m != nil {
		return m.Usage
	}
	return nil
}

type Provisioner struct {
	Id               *string    `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	Version          *string    `protobuf:"bytes,2,req,name=version" json:"version,omitempty"`
	Hostname         *string    `protobuf:"bytes,3,req,name=hostname" json:"hostname,omitempty"`
	IpAddress        *string    `protobuf:"bytes,4,req,name=ipAddress" json:"ipAddress,omitempty"`
	AzName           *string    `protobuf:"bytes,5,req,name=azName" json:"azName,omitempty"`
	MachineClass     *string    `protobuf:"bytes,6,req,name=machineClass" json:"machineClass,omitempty"`
	Started          *uint64    `protobuf:"varint,7,req,name=started" json:"started,omitempty"`
	LastUpdate       *uint64    `protobuf:"varint,8,req,name=lastUpdate" json:"lastUpdate,omitempty"`
	Machine          *Machine   `protobuf:"bytes,9,req,name=machine" json:"machine,omitempty"`
	Processes        []*Service `protobuf:"bytes,10,rep,name=processes" json:"processes,omitempty"`
	Containers       []*Service `protobuf:"bytes,11,rep,name=containers" json:"containers,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *Provisioner) Reset()         { *m = Provisioner{} }
func (m *Provisioner) String() string { return proto.CompactTextString(m) }
func (*Provisioner) ProtoMessage()    {}

func (m *Provisioner) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Provisioner) GetVersion() string {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return ""
}

func (m *Provisioner) GetHostname() string {
	if m != nil && m.Hostname != nil {
		return *m.Hostname
	}
	return ""
}

func (m *Provisioner) GetIpAddress() string {
	if m != nil && m.IpAddress != nil {
		return *m.IpAddress
	}
	return ""
}

func (m *Provisioner) GetAzName() string {
	if m != nil && m.AzName != nil {
		return *m.AzName
	}
	return ""
}

func (m *Provisioner) GetMachineClass() string {
	if m != nil && m.MachineClass != nil {
		return *m.MachineClass
	}
	return ""
}

func (m *Provisioner) GetStarted() uint64 {
	if m != nil && m.Started != nil {
		return *m.Started
	}
	return 0
}

func (m *Provisioner) GetLastUpdate() uint64 {
	if m != nil && m.LastUpdate != nil {
		return *m.LastUpdate
	}
	return 0
}

func (m *Provisioner) GetMachine() *Machine {
	if m != nil {
		return m.Machine
	}
	return nil
}

func (m *Provisioner) GetProcesses() []*Service {
	if m != nil {
		return m.Processes
	}
	return nil
}

func (m *Provisioner) GetContainers() []*Service {
	if m != nil {
		return m.Containers
	}
	return nil
}

func init() {
}
