// Code generated by protoc-gen-go.
// source: github.com/HailoOSS/provisioning-manager-service/proto/describerunlevels/describerunlevels.proto
// DO NOT EDIT!

/*
Package com_HailoOSS_kernel_provisioningmanager_describerunlevels is a generated protocol buffer package.

It is generated from these files:
	github.com/HailoOSS/provisioning-manager-service/proto/describerunlevels/describerunlevels.proto

It has these top-level messages:
	RunLevel
	Request
	Response
*/
package com_HailoOSS_kernel_provisioningmanager_describerunlevels

import proto "github.com/HailoOSS/protobuf/proto"
import json "encoding/json"
import math "math"
import com_HailoOSS_kernel_provisioningmanager "github.com/HailoOSS/provisioning-manager-service/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type RunLevel struct {
	Level            *com_HailoOSS_kernel_provisioningmanager.Level `protobuf:"varint,1,req,name=level,enum=com.HailoOSS.kernel.provisioningmanager.Level" json:"level,omitempty"`
	Description      *string                                        `protobuf:"bytes,3,req,name=description" json:"description,omitempty"`
	XXX_unrecognized []byte                                         `json:"-"`
}

func (m *RunLevel) Reset()         { *m = RunLevel{} }
func (m *RunLevel) String() string { return proto.CompactTextString(m) }
func (*RunLevel) ProtoMessage()    {}

func (m *RunLevel) GetLevel() com_HailoOSS_kernel_provisioningmanager.Level {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return com_HailoOSS_kernel_provisioningmanager.Level_HALT
}

func (m *RunLevel) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

type Request struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}

type Response struct {
	RunLevels        []*RunLevel `protobuf:"bytes,1,rep,name=runLevels" json:"runLevels,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}

func (m *Response) GetRunLevels() []*RunLevel {
	if m != nil {
		return m.RunLevels
	}
	return nil
}

func init() {
}
